on:
  push:
    branches:
      - docsify
  pull_request:
    branches:
      - master

name: Build and deploy dokumentation

jobs:
  build_and_deploy_doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
